description: Simple IPCLOS based WAN setup to link two data centers
name: ebgp_wan_0.3

action:
  - name: Build
    jenkins_url: build_vmx_wan
    #must be one of NOOB, BUILD or TEST
    category: BUILD
    configuration:
      shell_command: 'write_yaml_files.py; python3 create_ansible_job_k8s.py; kubectl apply -f nita-ansible-job1.yaml; sleep 2; kubectl logs job/nita-ansible'

  - name: Dump configuration
    jenkins_url: dump_vmx_wan
    #must be one of NOOB, BUILD or TEST
    category: BUILD
    configuration:
      shell_command: 'write_yaml_files.py; kubectl apply -f nita-ansible-job1.yaml'
